services:
  app:
    build: .
    container_name: peroxidizer
    command: >
      sh -c "python app.py --reload &&
            tail -F anything"
    tty: true
    ports:
      - 80:80
    volumes:
      - .:/app